name = "invoice-generator"
compatibility_date = "2024-01-01"
main = "workers-site/index.js"
pages_build_output_dir = "dist"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[env.production]
workers_dev = true
