name = "invoice-generator"
compatibility_date = "2024-11-06"
compatibility_flags = [ "nodejs_compat_v2" ]
pages_build_output_dir = "./dist"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
