name = "invoice-generator"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm run build"

[env.production]
workers_dev = true

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
